### PR TITLE
Hosted payments

### PR DESCRIPTION
**Pull request by siddii**
Pull request for the recently added Hosted Payments feature - https://www.simplify.com/commerce/docs/tools/hosted-payments

Let me know if you have any questions.

Thanks!

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
Hi @siddii,

I have a small improvement on new feature hosted payment:
When the API key is incorrect, an error is supposed to be shown. Even if it seems to fade in, it disappears immediately after the animation ended. Can you fix that ?

I have also seen that the translation system has never been added to the templates. Can you please write ```{l s="<Your text>" mod="simplifycommerce"}``` (Even you do not translate them after that) ?
In example, the line following line https://github.com/PrestaShop/simplifycommerce/blob/d0d8ec52019015a40092e370d19454e15e0da395/views/templates/hook/module-wrapper.tpl#L37
should be 
```php
<h1>{l s='Start accepting payments now.' mod='simplifycommerce'}</h1>
```
instead of
```php
<h1>Start accepting payments now.</h1>
```

Thanks

**Comment by siddii** [comment]
@Quetzacoalt91 - I tried to replicate the issue you mentioned and couldn't. Let me know if this is what you are trying to do.

prestashopsettingsconfiguration

**Comment by Quetzacoalt91** [comment]
Hi @siddii,

Sorry, I did not give you enough details to reproduce the error. I was talking about an error shown on the payment page:
capture du 2015-01-28 15 37 54
On the screenshot, the panel was currently fading in. And when the animation is done, it immediately disappears.

For the translations, I only gave you an example. I was expecting you to add the translation tag on every texts in every tpl files.

**Comment by siddii** [comment]
Got it. I'll look into those.

**Comment by siddii** [comment]
@Quetzacoalt91 - I made some updates to fix those issues. And also, please test both HTTP & HTTPS scenarios.

Thanks!

**Comment by Quetzacoalt91** [comment]
Hi @siddii,

Thanks for the tip. I just tried to pay in Hosted Payment mode with HTTP and I got an error. When I click on the button "Pay now", I am redirected to the simplify website (Is it expected ?) and I get the following screen:
capture du 2015-01-29 10 05 42

On HTTPS, everything works.

**Comment by siddii** [comment]
Yes, by design on HTTP flow, we redirect to simplify's website for accepting payment information. 

Are you using Live API keys to run these tests? If yes, we do have a check if the request comes from a trusted domain (in this case its the prestashop's store website url). 

It should match the value on "Simplify Dashboard" (Account Settings -> Merchant Settings -> Hosted Payment - Redirect URL). Can you please check that value & try again?

If you use Sandbox API keys, it should work fine without this domain validation.

**Comment by Quetzacoalt91** [comment]
Hi @siddii,

Okay for the HTTP flow which is expected.
No we do not use live API keys to test the payment modules, we want to leave our credit cards alone. :)

Actually, I did not even filled the live part. Only the sandbox one.

**Comment by siddii** [comment]
Hi @Quetzacoalt91,

Currently there is a url validation limitation on not allowing localhost urls. Can you try 127.0.0.1 or something else for the prestashop url & see if it works?

Thanks!

**Comment by siddii** [comment]
Awesome... Thanks a lot :+1:  Any idea when this will be available on the core installation?

**Comment by Quetzacoalt91** [comment]
Hi @siddii,

Yes the module was working properly with an external URL, so I merged the pull-request.
For your question, the changes will be available from tomorrow.

Regards

**Pull request merged**
