### PR TITLE
Multiple currency support

### PR DESCRIPTION
**Pull request by siddii**
This pull request includes changes related to supporting Simplify Commerce in multiple currencies (more than USD) and other minor docs updates & cleanup.

### CODE REVIEW

**Comment by Mekki78** [comment]
Hello @siddii 

Please upgrade module version in  simplifycommerce.php

**Comment by siddii** [comment]
@Mekki78 - Its updated. Please let me know if anything else needs to be done.

**Comment by siddii** [comment]
@Mekki78 - Just checking to see if you had a chance to look at this PR.

**Comment by siddii** [comment]
@Mekki78 - Wondering any updates on this PR?

**Comment by mmoustai** [comment]
Hello @siddii 

I was speaking about this one :)

download 15

I change the file, have a great day,
Regards,

**Pull request merged**
